# Generated by Django 5.2.6 on 2025-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'United States'), ('UK', 'United Kingdom'), ('CAN', 'Canada'), ('AUS', 'Australia'), ('IND', 'India'), ('BRAZIL', 'Brazil'), ('FRA', 'France'), ('GER', 'Germany'), ('JPN', 'Japan'), ('CHN', 'China'), ('OTHER', 'Other')], max_length=100, null=True)),
            ],
        ),
    ]
